### ISSUE TITLE
Please provide the AppImage for download

### ISSUE THREAD

**Issue by probonopd** [Fraktal-JS/fraktal#3]
https://github.com/Fraktal-JS/fraktal/blob/78ccfaf7f94ed40f06bcfd2f4e7075b3c04e1dc4/package.json#L41

Please provide the AppImage for download on https://github.com/Fraktal-JS/fraktal/releases, thanks.

**Comment by a1icja** [comment]
We have been manually deleting them. I will re-run the build later and leave the files in.

**Comment by probonopd** [comment]
> We have been manually deleting them.

May I ask for the reason for that?

**Comment by a1icja** [comment]
I was previously unaware of what the file did. Nothing else to it. The file will be left in for all future releases.

**Comment by a1icja** [comment]
Fixed for latest release.
