### ISSUE TITLE
gpodder.net integration

### ISSUE THREAD

**Issue by tdemin** [Fraktal-JS/fraktal#8]
gpodder.net provides a neat service for syncing your podcatchers. Its support is already implemented in gPodder, AntennaPod and a few other apps. 

I know the app is still in beta state, yet this is a good feature request for the future. :)

**Comment by a1icja** [comment]
After quickly glossing over their API documentation, this service provides solutions for many features that we want to add (podcast search, syncing, etc.). I will be looking further into the API and how it can be implemented into Fraktal. Thanks!
